Fix build due to unknown fluid_assert
In file included from /fluidsynth/src/rvoice/fluid_iir_filter.h:23:0,
                 from /fluidsynth/src/rvoice/fluid_iir_filter_impl.cpp:20:
/fluidsynth/src/rvoice/fluid_iir_filter_impl.cpp: In function 'void fluid_iir_filter_apply_local(fluid_iir_filter_t*, fluid_real_t*, unsigned int)':
/fluidsynth/src/utils/fluidsynth_priv.h:338:25: error: there are no arguments to 'fluid_assert' that depend on a template parameter, so a declaration of 'fluid_assert' must be available [-fpermissive]
 #define FLUID_ASSERT(a) fluid_assert(a)
                         ^
/fluidsynth/src/rvoice/fluid_iir_filter_impl.cpp:200:13: note: in expansion of macro 'FLUID_ASSERT'
             FLUID_ASSERT(dsp_hist1 == dsp_hist1);
             ^~~~~~~~~~~~
/fluidsynth/src/utils/fluidsynth_priv.h:338:25: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
 #define FLUID_ASSERT(a) fluid_assert(a)
                         ^
/fluidsynth/src/rvoice/fluid_iir_filter_impl.cpp:200:13: note: in expansion of macro 'FLUID_ASSERT'
             FLUID_ASSERT(dsp_hist1 == dsp_hist1);

...